export function serializeFundingApplication(application) {
  if (!application) return null;

  return {
    id: application.id,
    userId: application.userId,
    status: application.status,
    progress: application.progress,
    fullName: application.fullName,
    email: application.email,
    phone: application.phone,
    city: application.city,
    state: application.state,
    startupName: application.startupName,
    website: application.website,
    socialLinks: application.socialLinks,
    industry: application.industry,
    stage: application.stage,
    problem: application.problem,
    solution: application.solution,
    targetAudience: application.targetAudience,
    revenue: application.revenue,
    profit: application.profit,
    customers: application.customers,
    fundingRaised: application.fundingRaised,
    growthMetrics: application.growthMetrics,
    amountRequested: application.amountRequested,
    equityOffered: application.equityOffered,
    useOfFunds: application.useOfFunds,
    pitchVideoUrl: application.pitchVideoUrl,
    pitchDeckUrl: application.pitchDeckUrl,
    submittedAt: application.submittedAt?.toISOString?.() ?? application.submittedAt ?? null,
    reviewedAt: application.reviewedAt?.toISOString?.() ?? application.reviewedAt ?? null,
    reviewNotes: application.reviewNotes ?? null,
    createdAt: application.createdAt?.toISOString?.() ?? application.createdAt ?? null,
    updatedAt: application.updatedAt?.toISOString?.() ?? application.updatedAt ?? null,
  };
}
