import { z } from 'zod';

export const CreateFundingApplicationSchema = z.object({
  fullName: z.string().optional(),
  email: z.string().email().optional(),
  phone: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  startupName: z.string().optional(),
  website: z.string().optional(),
  socialLinks: z.union([z.string(), z.array(z.string())]).optional(),
  industry: z.string().optional(),
  stage: z.string().optional(),
  problem: z.string().optional(),
  solution: z.string().optional(),
  targetAudience: z.string().optional(),
  revenue: z.string().optional(),
  profit: z.string().optional(),
  customers: z.string().optional(),
  fundingRaised: z.string().optional(),
  growthMetrics: z.string().optional(),
  amountRequested: z.union([z.number(), z.string()]).optional(),
  equityOffered: z.union([z.number(), z.string()]).optional(),
  useOfFunds: z.string().optional(),
  pitchVideoUrl: z.string().optional(),
  pitchDeckUrl: z.string().optional(),
});
